# Head Players Data

In [1]:
import pandas as pd

In [2]:
players = pd.read_csv(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\serie_a\players\players_serie_a_14-15.csv')
players

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,season,league
0,1513,Mauro Icardi,36,2897,22,20.040535,6,4.607650,121,34,4,0,F S,Inter,18,16.234041,23.242989,4.910617,2014-2015,serie_a
1,1955,Luca Toni,38,3228,22,21.204769,2,2.914252,125,27,3,0,F S,Verona,18,16.636976,18.810562,3.106042,2014-2015,serie_a
2,3848,Carlos Tévez,32,2594,20,13.372144,7,5.016580,114,61,6,0,F M S,Juventus,18,10.327029,20.007632,8.907537,2014-2015,serie_a
3,1293,Gonzalo Higuaín,37,2786,18,21.097412,7,4.082174,113,49,5,0,F S,Napoli,15,15.768320,22.711577,4.917353,2014-2015,serie_a
4,2014,Jérémy Menez,33,2713,16,10.936869,4,4.379692,78,46,3,1,F M S,AC Milan,8,4.846598,13.755916,6.889687,2014-2015,serie_a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,4024,Michu,3,147,0,0.304196,0,1.011195,2,4,1,0,M S,Napoli,0,0.304196,1.106812,0.439700,2014-2015,serie_a
570,4026,Paulo Barreto,1,2,0,0.000000,0,0.000000,0,0,0,0,S,Torino,0,0.000000,0.000000,0.000000,2014-2015,serie_a
571,4027,Sol Bamba,1,90,0,0.000000,0,0.000000,0,0,1,0,D,Palermo,0,0.000000,0.000000,0.000000,2014-2015,serie_a
572,4029,Tiberio Guarente,1,6,0,0.000000,0,0.000000,0,0,0,0,S,Empoli,0,0.000000,0.000000,0.000000,2014-2015,serie_a
573,4031,Jonathan,2,174,0,0.115653,0,0.589493,1,6,0,0,D M,Inter,0,0.115653,0.683870,0.515159,2014-2015,serie_a

# Merge CSVs into one

### Merge all bundesliga Players CSVs into one

In [4]:
import os
import pandas as pd

# Folder containing CSV files
folder_path = r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\bundesliga\shots'

# List all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Iterate through each CSV file, add a 'season' column, and save it
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    # Extract the league from the file name
    league = file.split('_')[1]
    # # Extract the year from the file name
    # year = file.split('_')[-1].split('.')[0]
    # start_year = int(year[:2]) + 2000
    # end_year = int(year[-2:]) + 2000
    # year_range = f"{start_year}-{end_year}"
    # Read the CSV file
    df = pd.read_csv(file_path)
    # Add a 'league' column with the corresponding league
    df['league'] = league
    # Add a 'season' column with the corresponding year range
    # df['season'] = year_range
    # Save the updated CSV file
    df.to_csv(file_path, index=False)

# Merge all CSVs into one
all_csv_data = [pd.read_csv(os.path.join(folder_path, file)) for file in csv_files]

# Concatenate all dataframes
shots_bundesliga_df = pd.concat(all_csv_data, ignore_index=True)

# Save the merged dataframe to a single CSV file
shots_bundesliga_df.to_csv(os.path.join(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\bundesliga', 'shots_bundesliga_dataset.csv'), index=False)

### Merge all epl Players CSVs into one

In [5]:
import os
import pandas as pd

# Folder containing CSV files
folder_path = r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\epl\shots'

# List all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Iterate through each CSV file, add a 'season' column, and save it
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    # Extract the league from the file name
    league = file.split('_')[1]
    # Extract the year from the file name
    # year = file.split('_')[-1].split('.')[0]
    # start_year = int(year[:2]) + 2000
    # end_year = int(year[-2:]) + 2000
    # year_range = f"{start_year}-{end_year}"
    # Read the CSV file
    df = pd.read_csv(file_path)
    # Add a 'league' column with the corresponding league
    df['league'] = league
    # Add a 'season' column with the corresponding year range
    # df['season'] = year_range
    # Save the updated CSV file
    df.to_csv(file_path, index=False)

# Merge all CSVs into one
all_csv_data = [pd.read_csv(os.path.join(folder_path, file)) for file in csv_files]

# Concatenate all dataframes
shots_epl_df = pd.concat(all_csv_data, ignore_index=True)

# Save the merged dataframe to a single CSV file
shots_epl_df.to_csv(os.path.join(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\epl', 'shots_epl_dataset.csv'), index=False)

### Merge all la_liga Players CSVs into one

In [6]:
import os
import pandas as pd

# Folder containing CSV files
folder_path = r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\la_liga\shots'

# List all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Iterate through each CSV file, add a 'season' column, and save it
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    # Extract the league from the file name
    league = file.split('_')[1] + '_liga'
    # Extract the year from the file name
    # year = file.split('_')[-1].split('.')[0]
    # start_year = int(year[:2]) + 2000
    # end_year = int(year[-2:]) + 2000
    # year_range = f"{start_year}-{end_year}"
    # Read the CSV file
    df = pd.read_csv(file_path)
    # Add a 'league' column with the corresponding league
    df['league'] = league
    # Add a 'season' column with the corresponding year range
    # df['season'] = year_range
    # Save the updated CSV file
    df.to_csv(file_path, index=False)

# Merge all CSVs into one
all_csv_data = [pd.read_csv(os.path.join(folder_path, file)) for file in csv_files]

# Concatenate all dataframes
shots_la_liga_df = pd.concat(all_csv_data, ignore_index=True)

# Save the merged dataframe to a single CSV file
shots_la_liga_df.to_csv(os.path.join(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\la_liga', 'shots_la_liga_dataset.csv'), index=False)

### Merge all ligue_1 Players CSVs into one

In [7]:
import os
import pandas as pd

# Folder containing CSV files
folder_path = r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\ligue_1\shots'

# List all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Iterate through each CSV file, add a 'season' column, and save it
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    # Extract the league from the file name
    league = file.split('_')[1] + '_1'
    # Extract the year from the file name
    # year = file.split('_')[-1].split('.')[0]
    # start_year = int(year[:2]) + 2000
    # end_year = int(year[-2:]) + 2000
    # year_range = f"{start_year}-{end_year}"
    # Read the CSV file
    df = pd.read_csv(file_path)
    # Add a 'league' column with the corresponding league
    df['league'] = league
    # Add a 'season' column with the corresponding year range
    # df['season'] = year_range
    # Save the updated CSV file
    df.to_csv(file_path, index=False)

# Merge all CSVs into one
all_csv_data = [pd.read_csv(os.path.join(folder_path, file)) for file in csv_files]

# Concatenate all dataframes
shots_ligue_1_df = pd.concat(all_csv_data, ignore_index=True)

# Save the merged dataframe to a single CSV file
shots_ligue_1_df.to_csv(os.path.join(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\ligue_1', 'shots_ligue_1_dataset.csv'), index=False)

### Merge all serie_a Players CSVs into one

In [8]:
import os
import pandas as pd

# Folder containing CSV files
folder_path = r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\serie_a\shots'

# List all CSV files in the folder
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

# Iterate through each CSV file, add a 'season' column, and save it
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    # Extract the league from the file name
    league = file.split('_')[1] + '_a'
    # Extract the year from the file name
    # year = file.split('_')[-1].split('.')[0]
    # start_year = int(year[:2]) + 2000
    # end_year = int(year[-2:]) + 2000
    # year_range = f"{start_year}-{end_year}"
    # Read the CSV file
    df = pd.read_csv(file_path)
    # Add a 'league' column with the corresponding league
    df['league'] = league
    # Add a 'season' column with the corresponding year range
    # df['season'] = year_range
    # Save the updated CSV file
    df.to_csv(file_path, index=False)

# Merge all CSVs into one
all_csv_data = [pd.read_csv(os.path.join(folder_path, file)) for file in csv_files]

# Concatenate all dataframes
shots_serie_a_df = pd.concat(all_csv_data, ignore_index=True)

# Save the merged dataframe to a single CSV file
shots_serie_a_df.to_csv(os.path.join(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets\serie_a', 'shots_serie_a_dataset.csv'), index=False)

# Merge all leagues

In [11]:
import os
import pandas as pd

# Define the folder path where the league folders are located
folder_path = r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\datasets'

# List all folders (leagues) in the datasets folder
leagues_folders = [f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f))]

# Create an empty list to store DataFrames of each league
dataframes = []

# Iterate through each league folder and read CSV files
for league in leagues_folders:
    league_folder_path = os.path.join(folder_path, league)
    csv_files = [file for file in os.listdir(league_folder_path) if file.endswith('.csv')]
    
    # Read each CSV file and append it to the list of DataFrames
    for file in csv_files:
        file_path = os.path.join(league_folder_path, file)
        df = pd.read_csv(file_path)
        dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
merged_df = pd.concat(dataframes, ignore_index=True)

# Save the merged DataFrame to a new CSV file
merged_df.to_csv('shots_of_leagues_dataset.csv', index=False)

In [13]:
import pandas as pd

# Read the merged CSV file
df = pd.read_csv('shots_of_leagues_dataset.csv')
df.head()

C:\Users\Youcode\AppData\Local\Temp\ipykernel_15752\1230872287.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('shots_of_leagues_dataset.csv')

,id,minute,result,X,Y,xG,player,h_a,player_id,situation,...,shotType,match_id,h_team,a_team,h_goals,a_goals,date,player_assisted,lastAction,league
0,30358.0,5.0,MissedShots,0.923,0.464,0.141077,Leroy Sané,h,337.0,OpenPlay,...,LeftFoot,5159.0,Schalke 04,VfB Stuttgart,3.0,2.0,2015-05-02 14:30:00,Leon Goretzka,Pass,bundesliga
1,30359.0,6.0,BlockedShot,0.764,0.427,0.012746,Roman Neustädter,h,346.0,OpenPlay,...,RightFoot,5159.0,Schalke 04,VfB Stuttgart,3.0,2.0,2015-05-02 14:30:00,NaN,Aerial,bundesliga
2,30360.0,8.0,Goal,0.929,0.490,0.530869,Klaas-Jan Huntelaar,h,340.0,OpenPlay,...,RightFoot,5159.0,Schalke 04,VfB Stuttgart,3.0,2.0,2015-05-02 14:30:00,NaN,BlockedPass,bundesliga
3,30362.0,13.0,MissedShots,0.829,0.555,0.075300,Dennis Aogo,h,334.0,OpenPlay,...,RightFoot,5159.0,Schalke 04,VfB Stuttgart,3.0,2.0,2015-05-02 14:30:00,Klaas-Jan Huntelaar,Pass,bundesliga
4,30363.0,14.0,SavedShot,0.889,0.610,0.232375,Leroy Sané,h,337.0,OpenPlay,...,LeftFoot,5159.0,Schalke 04,VfB Stuttgart,3.0,2.0,2015-05-02 14:30:00,Eric Maxim Choupo-Moting,TakeOn,bundesliga

In [1]:
import pandas as pd

# Read the merged CSV file
df = pd.read_csv('players_of_leagues_dataset.csv')

df = df.rename(columns={'id': 'player_id'})

# Define the desired column order
desired_columns_order = [
    'league', 'season',
    'player_id', 'player_name', 'team_title', 'position', 
    'games', 'time', 'goals', 'assists', 'xG', 'xA', 'shots', 'key_passes', 'yellow_cards', 'red_cards' , 'npg', 'npxG','xGChain', 'xGBuildup',
]

# Reorder columns in DataFrame
df = df[desired_columns_order]

# Save the updated DataFrame to a new CSV file
df.to_csv('players_of_leagues_dataset.csv', index=False)

In [3]:
df

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,bundesliga,2014-2015,356,Alexander Meier,Eintracht Frankfurt,F M S,26,2209,19,2,15.395941,1.268694,80,22,0,0,16,12.364834,12.408789,1.915658
1,bundesliga,2014-2015,227,Robert Lewandowski,Bayern Munich,F M S,31,2493,17,5,17.722183,4.644013,104,32,0,0,16,16.964407,23.315430,4.924822
2,bundesliga,2014-2015,392,Arjen Robben,Bayern Munich,D F M S,21,1681,17,7,10.364112,7.505970,88,50,0,0,15,8.848720,20.820983,8.605793
3,bundesliga,2014-2015,158,Bas Dost,Wolfsburg,F S,21,1532,16,4,11.341977,2.659186,43,15,1,0,16,11.341977,15.911891,2.538306
4,bundesliga,2014-2015,318,Pierre-Emerick Aubameyang,Borussia Dortmund,F M S,33,2724,16,6,15.396760,6.378020,102,46,4,0,14,13.881207,20.852728,2.512650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21006,serie_a,2021-2022,10042,Aimar Sher,Spezia,S,1,41,0,0,0.000000,0.000000,0,0,0,0,0,0.000000,0.047647,0.047647
21007,serie_a,2021-2022,10073,Adam Obert,Cagliari,S,2,25,0,0,0.000000,0.000000,0,0,0,0,0,0.000000,0.000000,0.000000
21008,serie_a,2021-2022,10084,Cristian Volpato,Roma,S,1,1,0,0,0.000000,0.000000,0,0,0,0,0,0.000000,0.000000,0.000000
21009,serie_a,2021-2022,10123,Filippo Distefano,Fiorentina,S,1,1,0,0,0.000000,0.000000,0,0,0,0,0,0.000000,0.000000,0.000000
21010,serie_a,2021-2022,10139,Mattia Zanotti,Inter,S,1,7,0,0,0.000000,0.123592,0,1,0,0,0,0.000000,0.123592,0.123592

# Split Data

In [1]:
import pandas as pd

data=pd.read_csv(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\bi\players_of_leagues_dataset.csv')
data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,bundesliga,2014-2015,356,Alexander Meier,Eintracht Frankfurt,F M S,26,2209,19,2,15.395941,1.268694,80,22,0,0,16,12.364834,12.408789,1.915658
1,bundesliga,2014-2015,227,Robert Lewandowski,Bayern Munich,F M S,31,2493,17,5,17.722183,4.644013,104,32,0,0,16,16.964407,23.315430,4.924822
2,bundesliga,2014-2015,392,Arjen Robben,Bayern Munich,D F M S,21,1681,17,7,10.364112,7.505970,88,50,0,0,15,8.848720,20.820983,8.605793
3,bundesliga,2014-2015,158,Bas Dost,Wolfsburg,F S,21,1532,16,4,11.341977,2.659186,43,15,1,0,16,11.341977,15.911891,2.538306
4,bundesliga,2014-2015,318,Pierre-Emerick Aubameyang,Borussia Dortmund,F M S,33,2724,16,6,15.396760,6.378020,102,46,4,0,14,13.881207,20.852728,2.512650

In [2]:
# Split the data based on the 'league' column
csv_data = data[data['league'].isin(['bundesliga', 'epl', 'la_liga'])]
json_data = data[data['league'] == 'ligue_1']
sql_data = data[data['league'] == 'serie_a']

# Save the split data to respective files
csv_data.to_csv(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\bi\bi_dataset\csv_players.csv', index=False)
json_data.to_json(r'C:\Users\Youcode\Desktop\8 Months\Fil Rouge\bi\bi_dataset\json_players.json', orient='records', lines=True)

In [3]:
csv_data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,bundesliga,2014-2015,356,Alexander Meier,Eintracht Frankfurt,F M S,26,2209,19,2,15.395941,1.268694,80,22,0,0,16,12.364834,12.408789,1.915658
1,bundesliga,2014-2015,227,Robert Lewandowski,Bayern Munich,F M S,31,2493,17,5,17.722183,4.644013,104,32,0,0,16,16.964407,23.315430,4.924822
2,bundesliga,2014-2015,392,Arjen Robben,Bayern Munich,D F M S,21,1681,17,7,10.364112,7.505970,88,50,0,0,15,8.848720,20.820983,8.605793
3,bundesliga,2014-2015,158,Bas Dost,Wolfsburg,F S,21,1532,16,4,11.341977,2.659186,43,15,1,0,16,11.341977,15.911891,2.538306
4,bundesliga,2014-2015,318,Pierre-Emerick Aubameyang,Borussia Dortmund,F M S,33,2724,16,6,15.396760,6.378020,102,46,4,0,14,13.881207,20.852728,2.512650

In [4]:
json_data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
12218,ligue_1,2014-2015,3277,Alexandre Lacazette,Lyon,F M,33,2860,27,6,18.597955,6.063526,96,53,6,0,19,11.757099,19.622068,6.380010
12219,ligue_1,2014-2015,4747,André-Pierre Gignac,Marseille,F M S,38,3118,21,2,16.700735,2.281485,124,22,3,0,19,14.420450,17.878307,2.918049
12220,ligue_1,2014-2015,1741,Zlatan Ibrahimovic,Paris Saint Germain,F S,24,2002,19,6,18.945743,7.077434,87,37,3,0,11,12.104887,21.294307,7.169927
12221,ligue_1,2014-2015,3294,Edinson Cavani,Paris Saint Germain,F S,35,2666,18,1,22.860319,1.743023,111,14,2,1,15,20.580034,25.087476,5.913360
12222,ligue_1,2014-2015,464,Max Gradel,Saint-Etienne,F M S,31,2186,17,3,14.411365,5.481754,102,46,6,0,13,10.610889,14.291718,2.279516

In [5]:
sql_data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
16580,serie_a,2014-2015,1513,Mauro Icardi,Inter,F S,36,2897,22,6,20.040535,4.607650,121,34,4,0,18,16.234041,23.242989,4.910617
16581,serie_a,2014-2015,1955,Luca Toni,Verona,F S,38,3228,22,2,21.204769,2.914252,125,27,3,0,18,16.636976,18.810562,3.106042
16582,serie_a,2014-2015,3848,Carlos Tévez,Juventus,F M S,32,2594,20,7,13.372144,5.016580,114,61,6,0,18,10.327029,20.007632,8.907537
16583,serie_a,2014-2015,1293,Gonzalo Higuaín,Napoli,F S,37,2786,18,7,21.097412,4.082174,113,49,5,0,15,15.768320,22.711577,4.917353
16584,serie_a,2014-2015,2014,Jérémy Menez,AC Milan,F M S,33,2713,16,4,10.936869,4.379692,78,46,3,1,8,4.846598,13.755916,6.889687

In [6]:
# Save SQL data to SQL database
import pyodbc

In [7]:
# Define the connection parameters
server = '172.26.139.82,1433'
database = 'test'  
username = 'sa'
password = 'Fayssal@2004'
driver = '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.10.so.1.1'  # Adjust the path based on your installation

# Establish a connection
conn = pyodbc.connect(f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}')

# Create a cursor to execute SQL queries
cursor = conn.cursor()

InterfaceError: ('IM002', '[IM002] [Microsoft][Gestionnaire de pilotes ODBC] Source de données introuvable et nom de pilote non spécifié (0) (SQLDriverConnect)')

In [18]:
# Define your table creation query
create_table_query = '''
                    CREATE TABLE SerieAData (
                        league VARCHAR(50),
                        season VARCHAR(50),
                        player_id INT,
                        player_name VARCHAR(255),
                        team_title VARCHAR(255),
                        position VARCHAR(50),
                        games INT,
                        time INT,
                        goals INT,
                        assists INT,
                        xG FLOAT,
                        xA FLOAT,
                        shots INT,
                        key_passes INT,
                        yellow_cards INT,
                        red_cards INT,
                        npg INT,
                        npxG FLOAT,
                        xGChain FLOAT,
                        xGBuildup FLOAT
                    )
                    '''

# Execute the table creation query
conn.execute(create_table_query)

In [17]:
# Insert data into the InvoiceData table
for row in sql_data.itertuples():
    cursor.execute('INSERT INTO SerieAData (league, season, player_id, player_name, team_title, position, games, time, goals, assists, xG, xA, shots, key_passes, yellow_cards, red_cards, npg, npxG, xGChain, xGBuildup) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);', (
        row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17], row[18], row[19], row[20]
    ))

conn.commit()

In [18]:
# Close the database connection
conn.close()