In [1]:
import pandas as pd

data=pd.read_csv('players_of_leagues_dataset.csv')
data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,bundesliga,2014-2015,356,Alexander Meier,Eintracht Frankfurt,F M S,26,2209,19,2,15.395941,1.268694,80,22,0,0,16,12.364834,12.408789,1.915658
1,bundesliga,2014-2015,227,Robert Lewandowski,Bayern Munich,F M S,31,2493,17,5,17.722183,4.644013,104,32,0,0,16,16.964407,23.315430,4.924822
2,bundesliga,2014-2015,392,Arjen Robben,Bayern Munich,D F M S,21,1681,17,7,10.364112,7.505970,88,50,0,0,15,8.848720,20.820983,8.605793
3,bundesliga,2014-2015,158,Bas Dost,Wolfsburg,F S,21,1532,16,4,11.341977,2.659186,43,15,1,0,16,11.341977,15.911891,2.538306
4,bundesliga,2014-2015,318,Pierre-Emerick Aubameyang,Borussia Dortmund,F M S,33,2724,16,6,15.396760,6.378020,102,46,4,0,14,13.881207,20.852728,2.512650

In [3]:
# Split the data based on the 'league' column
csv_data = data[data['league'].isin(['bundesliga', 'epl', 'la_liga'])]
json_data = data[data['league'] == 'ligue_1']
api_data = data[data['league'] == 'serie_a']

# Save the split data to respective files
csv_data.to_csv('datasets/csv_players.csv', index=False)
json_data.to_json('datasets/json_players.json', orient='records', lines=True)
api_data.to_csv('datasets/api_players.csv', index=False)

In [4]:
csv_data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,bundesliga,2014-2015,356,Alexander Meier,Eintracht Frankfurt,F M S,26,2209,19,2,15.395941,1.268694,80,22,0,0,16,12.364834,12.408789,1.915658
1,bundesliga,2014-2015,227,Robert Lewandowski,Bayern Munich,F M S,31,2493,17,5,17.722183,4.644013,104,32,0,0,16,16.964407,23.315430,4.924822
2,bundesliga,2014-2015,392,Arjen Robben,Bayern Munich,D F M S,21,1681,17,7,10.364112,7.505970,88,50,0,0,15,8.848720,20.820983,8.605793
3,bundesliga,2014-2015,158,Bas Dost,Wolfsburg,F S,21,1532,16,4,11.341977,2.659186,43,15,1,0,16,11.341977,15.911891,2.538306
4,bundesliga,2014-2015,318,Pierre-Emerick Aubameyang,Borussia Dortmund,F M S,33,2724,16,6,15.396760,6.378020,102,46,4,0,14,13.881207,20.852728,2.512650

In [5]:
json_data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
12218,ligue_1,2014-2015,3277,Alexandre Lacazette,Lyon,F M,33,2860,27,6,18.597955,6.063526,96,53,6,0,19,11.757099,19.622068,6.380010
12219,ligue_1,2014-2015,4747,André-Pierre Gignac,Marseille,F M S,38,3118,21,2,16.700735,2.281485,124,22,3,0,19,14.420450,17.878307,2.918049
12220,ligue_1,2014-2015,1741,Zlatan Ibrahimovic,Paris Saint Germain,F S,24,2002,19,6,18.945743,7.077434,87,37,3,0,11,12.104887,21.294307,7.169927
12221,ligue_1,2014-2015,3294,Edinson Cavani,Paris Saint Germain,F S,35,2666,18,1,22.860319,1.743023,111,14,2,1,15,20.580034,25.087476,5.913360
12222,ligue_1,2014-2015,464,Max Gradel,Saint-Etienne,F M S,31,2186,17,3,14.411365,5.481754,102,46,6,0,13,10.610889,14.291718,2.279516

In [6]:
api_data.head()

,league,season,player_id,player_name,team_title,position,games,time,goals,assists,xG,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
16580,serie_a,2014-2015,1513,Mauro Icardi,Inter,F S,36,2897,22,6,20.040535,4.607650,121,34,4,0,18,16.234041,23.242989,4.910617
16581,serie_a,2014-2015,1955,Luca Toni,Verona,F S,38,3228,22,2,21.204769,2.914252,125,27,3,0,18,16.636976,18.810562,3.106042
16582,serie_a,2014-2015,3848,Carlos Tévez,Juventus,F M S,32,2594,20,7,13.372144,5.016580,114,61,6,0,18,10.327029,20.007632,8.907537
16583,serie_a,2014-2015,1293,Gonzalo Higuaín,Napoli,F S,37,2786,18,7,21.097412,4.082174,113,49,5,0,15,15.768320,22.711577,4.917353
16584,serie_a,2014-2015,2014,Jérémy Menez,AC Milan,F M S,33,2713,16,4,10.936869,4.379692,78,46,3,1,8,4.846598,13.755916,6.889687